version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./MUSICGEN_ROOT:/app/MUSICGEN_ROOT
      - ./HF_HOME:/app/HF_HOME
      - ./.container-cache:/root/.cache
      - ./venv:/app/audio-webui/venv
    environment:
      - ROCM_VISIBLE_DEVICES=all
    env_file:
      - .env
    ports:
      - 7860:7860
    stdin_open: true
    tty: true
    devices:
      - /dev/dri:/dev/dri
